package app.birdo.vpn.utils

import android.content.Context
import android.util.Log
import java.io.File
import java.security.MessageDigest

/**
 * Verifies integrity of JNI native libraries before loading.
 *
 * Mirrors the Windows client's wintun.dll SHA-256 verification.
 * Prevents loading of tampered wg-go or xray native libraries.
 */
object NativeLibraryVerifier {

    private const val TAG = "NativeLibVerify"

    /**
     * Known-good SHA-256 hashes of native libraries.
     * Populated at build time via the computeNativeLibHashes Gradle task.
     * On hash mismatch in release builds, library loading is blocked.
     *
     * To regenerate manually:
     *   sha256sum app/build/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libwg-go.so
     */
    private val KNOWN_HASHES: Map<String, String> by lazy {
        // Read hashes from BuildConfig fields generated by Gradle at release build time
        try {
            val clazz = app.birdo.vpn.BuildConfig::class.java
            val wgHash = clazz.getField("NATIVE_HASH_WG_GO").get(null) as? String ?: ""
            val xrayHash = clazz.getField("NATIVE_HASH_XRAY").get(null) as? String ?: ""
            // AUDIT-E1: BirdoPQ v1 KEM lib must be hashed too — without this,
            // an attacker who can swap just librosenpass_jni.so (e.g. via a
            // tampered downstream APK rebuild) could silently downgrade the
            // PQ PSK by returning attacker-known bytes from deriveSharedPsk().
            val rosenpassJniHash = runCatching {
                clazz.getField("NATIVE_HASH_ROSENPASS_JNI").get(null) as? String ?: ""
            }.getOrDefault("")
            buildMap {
                if (wgHash.isNotBlank()) put("wg-go", wgHash)
                if (xrayHash.isNotBlank()) {
                    put("xray", xrayHash)
                    put("Xray", xrayHash)
                }
                if (rosenpassJniHash.isNotBlank()) put("rosenpass_jni", rosenpassJniHash)
            }
        } catch (_: Exception) {
            // Fields don't exist (dev build) — skip verification
            emptyMap()
        }
    }

    /**
     * Verify a native library's SHA-256 hash before loading.
     *
     * Returns true if the library is trusted. Behaviour matrix:
     *
     * | Build   | Hash registered | File present | Hash matches | Result |
     * |---------|-----------------|--------------|--------------|--------|
     * | debug   | any             | any          | any          | true   |
     * | release | yes             | yes          | yes          | true   |
     * | release | yes             | yes          | no           | false  |
     * | release | yes             | no           | —            | false  |
     * | release | no              | any          | —            | false  |  ← AUDIT-E1: fail-CLOSED
     *
     * Previously the "no hash registered" case returned `true` (graceful
     * degrade), which silently disabled integrity verification if a
     * BuildConfig field went missing. Release builds now refuse to load
     * any unregistered library so a build-system regression cannot quietly
     * weaken the supply-chain check.
     */
    fun verifyLibrary(context: Context, libraryName: String): Boolean {
        if (app.birdo.vpn.BuildConfig.DEBUG) {
            Log.d(TAG, "Debug build — skipping native library verification for $libraryName")
            return true
        }

        val nativeLibDir = context.applicationInfo.nativeLibraryDir
        val libFile = File(nativeLibDir, "lib${libraryName}.so")

        if (!libFile.exists()) {
            Log.e(TAG, "Native library not found: ${libFile.absolutePath}")
            return false
        }

        val expectedHash = KNOWN_HASHES[libraryName]
        if (expectedHash.isNullOrBlank()) {
            if (!RootDetector.hasSigningFingerprintConfigured(context)) {
                Log.e(TAG, "INTEGRITY FAILURE: no hash and no release signing fingerprint for $libraryName")
                return false
            }
            if (!RootDetector.isPackageSignatureTrusted(context)) {
                Log.e(TAG, "INTEGRITY FAILURE: package signature is not trusted for $libraryName")
                return false
            }
            Log.w(TAG, "No registered hash for $libraryName; package signature check passed")
            return true
        }

        return try {
            val actualHash = sha256Hex(libFile)
            if (actualHash.equals(expectedHash, ignoreCase = true)) {
                Log.i(TAG, "Library $libraryName integrity verified")
                true
            } else {
                Log.e(TAG, "INTEGRITY FAILURE: $libraryName hash mismatch! Expected=$expectedHash Actual=$actualHash")
                false
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to verify $libraryName", e)
            false
        }
    }

    private fun sha256Hex(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().buffered().use { input ->
            val buffer = ByteArray(8192)
            var bytesRead: Int
            while (input.read(buffer).also { bytesRead = it } != -1) {
                digest.update(buffer, 0, bytesRead)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }
}
