package app.birdo.vpn.data.model

import app.birdo.vpn.di.NetworkModule
import app.birdo.vpn.shared.model.TransportFallbackReason
import com.networknt.schema.Error
import com.networknt.schema.InputFormat
import com.networknt.schema.Schema
import com.networknt.schema.SchemaLocation
import com.networknt.schema.SchemaRegistry
import com.networknt.schema.SpecificationVersion
import kotlinx.serialization.descriptors.elementNames
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.serializer
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * K5 connect contract — the SERIALIZED connect bodies against the backend's
 * own schema.
 *
 * `contract/vpn-protocol.schema.json` is generated by birdo-web from the code
 * that actually enforces the wire contract (class-validator on ConnectDto for
 * POST /vpn/connect, the `.strict()` zod schema for POST /vpn/multi-hop/connect)
 * and vendored here byte-for-byte. Both routes REFUSE unknown properties, so a
 * field renamed on either side is not "ignored" — it is a 400 on every connect.
 * That has happened: iOS once sent `serverId` for `serverNodeId` and every
 * connect failed outright (see the AUDIT-M-DRIFT note in APIClient.swift).
 *
 * [RequestSerializationTest] proves the models serialize at all. This test
 * proves the BYTES are what the server accepts: it encodes the real
 * [ConnectRequest] / [MultiHopConnectRequest] exactly as BirdoRepository builds
 * them, through the app's own [NetworkModule.json] (the Retrofit converter's
 * instance — a private `Json {}` here would not see an `explicitNulls` or
 * `encodeDefaults` change), and validates the output with a real Draft
 * 2020-12 validator. The mutation cases pin that the validator bites: an
 * unknown key, a renamed key, a broken pattern and an explicit null all FAIL.
 *
 * Refresh the vendored file with the command in contract/README.md; the
 * backend's protocol-schema.spec.ts refuses to merge a contract change without
 * regenerating it, so a drift shows up here, not in production.
 */
class ConnectContractTest {

    private companion object {
        /** Walk up from the test's working directory to the repo root. */
        val repoRoot: File by lazy {
            var dir = File("").absoluteFile
            while (!File(dir, "settings.gradle.kts").isFile) {
                dir = dir.parentFile
                    ?: error("settings.gradle.kts not found above ${File("").absolutePath}")
            }
            dir
        }

        const val SCHEMA_ID = "https://birdo.app/contract/vpn-protocol.schema.json"

        val schemaText: String by lazy {
            File(repoRoot, "contract/vpn-protocol.schema.json").readText()
        }

        val schemaDoc: JsonObject by lazy { Json.parseToJsonElement(schemaText).jsonObject }

        /**
         * Registered under its own `$id` so `#/$defs/...` fragments resolve
         * against the vendored document, not a string with no base IRI.
         */
        val registry: SchemaRegistry by lazy {
            SchemaRegistry.withDefaultDialect(SpecificationVersion.DRAFT_2020_12) { builder ->
                builder.schemas(mapOf(SCHEMA_ID to schemaText))
            }
        }

        fun definition(name: String): Schema =
            registry.getSchema(SchemaLocation.of("$SCHEMA_ID#/\$defs/$name"))

        val connectSchema: Schema by lazy { definition("ConnectRequest") }
        val multiHopSchema: Schema by lazy { definition("MultiHopConnectRequest") }

        /** Property names a definition declares — the whitelist the server enforces. */
        fun schemaProperties(name: String): Set<String> =
            schemaDoc["\$defs"]!!.jsonObject[name]!!.jsonObject["properties"]!!.jsonObject.keys

        // Shapes that satisfy the schema's patterns and lengths — the values
        // BirdoRepository really sends have exactly these forms.
        /** 32 bytes of Curve25519 in base64: 43 chars + '=' (schema pattern). */
        const val WG_PUBLIC_KEY = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
        /** ML-KEM-1024 encapsulation key (1568 B) in base64 = 2092 chars; schema: 2080..2200. */
        val PQ_PUBLIC_KEY = "A".repeat(2092)
        const val DEVICE_ID = "ssaid:3f9c2a1b7e4d5c60"
        const val INTEGRITY_TOKEN = "eyJhbGciOiJIUzI1NiJ9.play-integrity.token"
    }

    /** The app's wire serializer — see NetworkModule. */
    private val json: Json = NetworkModule.json

    // ── Bodies exactly as BirdoRepository builds them ────────────────────

    /** Every field connectVpn() can set, set (stealth + adaptive-transport retry + PQ + Play). */
    private fun fullConnect() = ConnectRequest(
        serverNodeId = "node-nl-1",
        deviceName = "Pixel 9",
        deviceId = DEVICE_ID,
        // Declared on the model (and known to the server) though connectVpn()
        // never sets it today — "every field the model can emit" means every.
        preferredRegion = "eu-west",
        clientPublicKey = WG_PUBLIC_KEY,
        stealthMode = true,
        fallbackReason = TransportFallbackReason.HANDSHAKE_TIMEOUT,
        quantumProtection = true,
        pqClientPublicKey = PQ_PUBLIC_KEY,
        pqClientCanDecapsulate = true,
        integrityToken = INTEGRITY_TOKEN,
    )

    /** A first attempt on a non-Play build with PQ off: defaults stay off the wire. */
    private fun minimalConnect() = ConnectRequest(
        serverNodeId = "node-nl-1",
        deviceName = "Pixel 9",
        deviceId = DEVICE_ID,
        clientPublicKey = WG_PUBLIC_KEY,
        pqClientCanDecapsulate = false,
        integrityToken = null,
    )

    private fun fullMultiHop() = MultiHopConnectRequest(
        entryNodeId = "node-nl-1",
        exitNodeId = "node-de-2",
        deviceName = "Pixel 9",
        deviceId = DEVICE_ID,
        clientPublicKey = WG_PUBLIC_KEY,
        stealthMode = true,
        fallbackReason = TransportFallbackReason.TRANSPORT_BLOCKED,
        quantumProtection = true,
        pqClientPublicKey = PQ_PUBLIC_KEY,
        pqClientCanDecapsulate = true,
        integrityToken = INTEGRITY_TOKEN,
    )

    private fun minimalMultiHop() = MultiHopConnectRequest(
        entryNodeId = "node-nl-1",
        exitNodeId = "node-de-2",
        deviceName = "Pixel 9",
        deviceId = DEVICE_ID,
        clientPublicKey = WG_PUBLIC_KEY,
    )

    private fun encode(request: ConnectRequest): String =
        json.encodeToString(serializer<ConnectRequest>(), request)

    private fun encode(request: MultiHopConnectRequest): String =
        json.encodeToString(serializer<MultiHopConnectRequest>(), request)

    // ── Helpers ─────────────────────────────────────────────────────────

    private fun assertValid(schema: Schema, body: String) {
        val errors = schema.validate(body, InputFormat.JSON)
        assertTrue("expected the body to validate but got: ${errors.describe()}\nbody: $body", errors.isEmpty())
    }

    /** The mutation must be refused, and refused for the RIGHT reason. */
    private fun assertRefused(schema: Schema, body: String, keyword: String, property: String? = null) {
        val errors = schema.validate(body, InputFormat.JSON)
        val hit = errors.any { e ->
            // additionalProperties names the offender in `property`; every
            // other keyword only in the instance location (`/clientPublicKey`).
            e.keyword == keyword && (
                property == null ||
                    e.property == property ||
                    e.instanceLocation.toString().endsWith("/$property") ||
                    e.message.contains(property)
                )
        }
        assertTrue(
            "expected a '$keyword'${property?.let { " on $it" } ?: ""} refusal, got: ${errors.describe()}\nbody: $body",
            hit,
        )
    }

    private fun List<Error>.describe(): String =
        if (isEmpty()) "no errors" else joinToString("; ") { "${it.keyword}@${it.instanceLocation}: ${it.message}" }

    private fun String.mutate(transform: (MutableMap<String, JsonElement>) -> Unit): String {
        val fields = Json.parseToJsonElement(this).jsonObject.toMutableMap()
        transform(fields)
        return JsonObject(fields).toString()
    }

    private fun assertNoNulls(body: String) {
        val values = Json.parseToJsonElement(body).jsonObject
        assertTrue(
            "an explicit null reached the wire: $body — zod .optional() rejects null, only an ABSENT key passes",
            values.values.none { it is JsonNull },
        )
    }

    // ── The vendored file ───────────────────────────────────────────────

    @Test
    fun `vendored schema is birdo-web's authoritative generation for both connect routes`() {
        assertEquals(SCHEMA_ID, schemaDoc["\$id"]!!.jsonPrimitive.content)
        val status = schemaDoc["_status"]!!.jsonObject
        assertEquals("true", status["authoritative"]!!.jsonPrimitive.content)
        val definitions = status["definitions"]!!.jsonArray.map { it.jsonPrimitive.content }
        assertTrue("ConnectRequest missing from $definitions", "ConnectRequest" in definitions)
        assertTrue("MultiHopConnectRequest missing from $definitions", "MultiHopConnectRequest" in definitions)
        // Both routes refuse unknown keys — the whole reason a rename is fatal.
        for (name in listOf("ConnectRequest", "MultiHopConnectRequest")) {
            val def = schemaDoc["\$defs"]!!.jsonObject[name]!!.jsonObject
            assertEquals("$name must refuse unknown properties", JsonPrimitive(false), def["additionalProperties"])
        }
    }

    // ── Positive: the bodies the app sends validate ─────────────────────

    @Test
    fun `fully populated ConnectRequest validates against ConnectRequest`() {
        val body = encode(fullConnect())
        assertValid(connectSchema, body)
        assertNoNulls(body)
        // Every field the model can emit is on the wire AND known to the server.
        val keys = Json.parseToJsonElement(body).jsonObject.keys
        assertEquals(serializer<ConnectRequest>().descriptor.elementNames.toSet(), keys)
        assertTrue("unknown keys: ${keys - schemaProperties("ConnectRequest")}", keys.all { it in schemaProperties("ConnectRequest") })
    }

    @Test
    fun `minimal first-attempt ConnectRequest validates and keeps defaults off the wire`() {
        val body = encode(minimalConnect())
        assertValid(connectSchema, body)
        assertNoNulls(body)
        val keys = Json.parseToJsonElement(body).jsonObject.keys
        assertEquals(setOf("serverNodeId", "deviceName", "deviceId", "clientPublicKey"), keys)
    }

    @Test
    fun `fully populated MultiHopConnectRequest validates against MultiHopConnectRequest`() {
        val body = encode(fullMultiHop())
        assertValid(multiHopSchema, body)
        assertNoNulls(body)
        val keys = Json.parseToJsonElement(body).jsonObject.keys
        assertEquals(serializer<MultiHopConnectRequest>().descriptor.elementNames.toSet(), keys)
        assertTrue("unknown keys: ${keys - schemaProperties("MultiHopConnectRequest")}", keys.all { it in schemaProperties("MultiHopConnectRequest") })
    }

    @Test
    fun `minimal MultiHopConnectRequest validates and carries both hop ids`() {
        val body = encode(minimalMultiHop())
        assertValid(multiHopSchema, body)
        assertNoNulls(body)
        val fields = Json.parseToJsonElement(body).jsonObject
        assertEquals("node-nl-1", fields["entryNodeId"]?.jsonPrimitive?.content)
        assertEquals("node-de-2", fields["exitNodeId"]?.jsonPrimitive?.content)
    }

    @Test
    fun `every model field has a twin in the schema even when a test forgets to set it`() {
        // Independent of which fields the bodies above populate: a field added to
        // the Kotlin model without a backend twin is refused by the server on
        // the first connect that sets it.
        val connectFields = serializer<ConnectRequest>().descriptor.elementNames.toSet()
        assertTrue(
            "ConnectRequest fields the backend does not know: ${connectFields - schemaProperties("ConnectRequest")}",
            connectFields.all { it in schemaProperties("ConnectRequest") },
        )
        val multiHopFields = serializer<MultiHopConnectRequest>().descriptor.elementNames.toSet()
        assertTrue(
            "MultiHopConnectRequest fields the backend does not know: ${multiHopFields - schemaProperties("MultiHopConnectRequest")}",
            multiHopFields.all { it in schemaProperties("MultiHopConnectRequest") },
        )
        // The multi-hop twin's required pair is exactly what the model makes non-optional.
        val required = schemaDoc["\$defs"]!!.jsonObject["MultiHopConnectRequest"]!!.jsonObject["required"]!!
            .jsonArray.map { it.jsonPrimitive.content }.toSet()
        assertEquals(setOf("entryNodeId", "exitNodeId"), required)
    }

    @Test
    fun `TransportFallbackReason constants are exactly the schema enum`() {
        // The model comment says these MUST match the backend's @IsIn list; this
        // is the check. A typo here is a 400 on the retry a censored user needs.
        val schemaEnum = schemaDoc["\$defs"]!!.jsonObject["ConnectRequest"]!!.jsonObject["properties"]!!
            .jsonObject["fallbackReason"]!!.jsonObject["enum"]!!.jsonArray.map { it.jsonPrimitive.content }.toSet()
        val constants = setOf(
            TransportFallbackReason.HANDSHAKE_TIMEOUT,
            TransportFallbackReason.TRANSPORT_BLOCKED,
            TransportFallbackReason.DNS_BLOCKED,
        )
        assertEquals(schemaEnum, constants)
    }

    // ── Negative: the validator bites ───────────────────────────────────

    @Test
    fun `an unknown field is refused on both routes`() {
        val single = encode(fullConnect()).mutate { it["serverId"] = JsonPrimitive("node-nl-1") }
        assertRefused(connectSchema, single, keyword = "additionalProperties", property = "serverId")

        val multi = encode(fullMultiHop()).mutate { it["entryId"] = JsonPrimitive("node-nl-1") }
        assertRefused(multiHopSchema, multi, keyword = "additionalProperties", property = "entryId")
    }

    @Test
    fun `a renamed field is refused, and a renamed required field twice`() {
        // The real historical drift: serverNodeId sent as serverId.
        val single = encode(fullConnect()).mutate { it["serverId"] = it.remove("serverNodeId") ?: error("serverNodeId is not on the wire") }
        assertRefused(connectSchema, single, keyword = "additionalProperties", property = "serverId")

        // On multi-hop a renamed hop id is both unknown AND missing.
        val multi = encode(fullMultiHop()).mutate { it["entryId"] = it.remove("entryNodeId") ?: error("entryNodeId is not on the wire") }
        assertRefused(multiHopSchema, multi, keyword = "additionalProperties", property = "entryId")
        assertRefused(multiHopSchema, multi, keyword = "required", property = "entryNodeId")
    }

    @Test
    fun `a missing hop id is refused`() {
        val body = encode(fullMultiHop()).mutate { it.remove("exitNodeId") }
        assertRefused(multiHopSchema, body, keyword = "required", property = "exitNodeId")
    }

    @Test
    fun `a malformed clientPublicKey is refused on both routes`() {
        // 44 chars but not base64-with-trailing-'=': the pattern, not the length, must catch it.
        val bad = JsonPrimitive("A".repeat(44))
        assertRefused(connectSchema, encode(fullConnect()).mutate { it["clientPublicKey"] = bad }, keyword = "pattern", property = "clientPublicKey")
        assertRefused(multiHopSchema, encode(fullMultiHop()).mutate { it["clientPublicKey"] = bad }, keyword = "pattern", property = "clientPublicKey")
    }

    @Test
    fun `a fallbackReason outside the enum is refused`() {
        // The underscore spelling is the obvious typo; the server 400s it and the
        // censored user's retry is the one that fails.
        val body = encode(fullConnect()).mutate { it["fallbackReason"] = JsonPrimitive("handshake_timeout") }
        assertRefused(connectSchema, body, keyword = "enum", property = "fallbackReason")
    }

    @Test
    fun `a pqClientPublicKey below the ML-KEM-1024 floor is refused`() {
        val body = encode(fullConnect()).mutate { it["pqClientPublicKey"] = JsonPrimitive("A".repeat(2079)) }
        assertRefused(connectSchema, body, keyword = "minLength", property = "pqClientPublicKey")
    }

    @Test
    fun `an explicit null is refused - which is why encodeDefaults stays off`() {
        // NetworkModule.json keeps defaults (including null defaults) OFF the
        // wire. If someone turns on encodeDefaults or explicitNulls-with-nulls,
        // this is what the server sees: type violations on every optional.
        val body = encode(fullConnect()).mutate { it["integrityToken"] = JsonNull }
        assertRefused(connectSchema, body, keyword = "type", property = "integrityToken")
    }

    @Test
    fun `a boolean sent as a string is refused`() {
        val body = encode(fullMultiHop()).mutate { it["stealthMode"] = JsonPrimitive("true") }
        assertRefused(multiHopSchema, body, keyword = "type", property = "stealthMode")
    }
}
