package app.birdo.vpn.ui.components

import android.animation.ValueAnimator
import android.app.ActivityManager
import android.content.Context
import androidx.compose.animation.core.FastOutSlowInEasing
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.runtime.withFrameMillis
import androidx.compose.ui.Modifier
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.compose.LocalLifecycleOwner
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.isSpecified
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.translate
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalView
import app.birdo.vpn.data.model.VpnServer
import app.birdo.vpn.perf.GlobePerf
import app.birdo.vpn.perf.GlobePerfControls
import app.birdo.vpn.perf.GlobePerfState
import app.birdo.vpn.ui.theme.BirdoColors
import app.birdo.vpn.utils.CountryCoords
import kotlin.math.PI
import kotlin.math.acos
import kotlin.math.cos
import kotlin.math.min
import kotlin.math.sin
import kotlin.random.Random

/**
 * Mullvad-style 3D rotating orthographic globe.
 *
 * This is the first thing a new install sees, so its cost lands exactly on the
 * install -> first-open step, on the oldest hardware in the fleet.
 *
 * Performance-critical decisions:
 *
 *  - **No trigonometry in the continent loop** (v1.4.21). Cell longitudes are
 *    pre-folded into `cosPhi*cos(lon)` / `cosPhi*sin(lon)` products so the
 *    camera rotation becomes two multiply-adds, and the back-face cull runs
 *    BEFORE the work only visible cells need. See [GlobeGeometry]; the maths
 *    and the emitted-quad counts are pinned by `GlobeGeometryTest`.
 *  - **Brushes are cached across frames** ([GlobeBrushes]). `Brush.radialGradient`
 *    caches its native shader INSIDE the brush instance, so building a fresh
 *    instance per frame defeats that cache entirely. All six gradients are now
 *    keyed on disc geometry (and rebuilt via `remember` when the theme changes),
 *    so a steady-state frame constructs ZERO shaders. The two sun-tracking
 *    gradients keep a fixed centre and are moved with a canvas `translate`,
 *    which is a matrix push rather than a shader rebuild.
 *  - Land cell positions live in one flat `FloatArray`, walked by a single
 *    while loop. Three retained `Path` objects accumulate the squares per
 *    brightness bucket and are reused across frames via `Path.reset()`.
 *  - The great-circle connection arc is generated by slerp on the unit sphere
 *    and projected segment-by-segment, so it follows the curvature of the
 *    planet and naturally clips when it dips behind the limb.
 *  - All heavy rendering lives in a top-level `DrawScope` extension, dodging
 *    the Compose compiler stack-overflow that bit us on v1.3.10 CI.
 *
 * Allocation honesty. The previous version of this comment claimed the renderer
 * made "no Rect, Triple, Pair, list/iterator allocations" — true of the land
 * loop and false of everything below it, which is how ~12 allocations and 6
 * native shader constructions per frame survived two optimisation passes. What
 * is true now: the land, star, server-dot and gradient paths allocate nothing in
 * a steady-state frame. The arc path and Compose's own draw scope still do.
 * Do not restore a blanket "no allocations" claim without re-checking it.
 */
@Composable
fun WorldGlobe(
    servers: List<VpnServer>,
    selectedServerId: String?,
    isConnected: Boolean,
    modifier: Modifier = Modifier,
    autoRotate: Boolean = true,
    userLat: Double = 51.51,
    userLon: Double = -0.13,
) {
    val palette = BirdoColors.current
    val context = LocalContext.current

    // Cost profile for THIS device. Read once — neither the RAM tier nor the
    // heap class changes while the app is alive.
    val autoQuality = remember(context) { globeQualityFor(context) }
    // Debug builds (and a release built with -PperfOverlay=true) can pin the
    // tier from the perf HUD, so FULL and LITE can be compared on ONE device
    // instead of inferred across two. Constant-folds away otherwise.
    val quality = debugQualityOverride(autoQuality)

    // Label every frame produced while this globe is composed with its tier, so
    // JankStats can partition its histogram into globe-on and globe-off. This
    // runs on composition and on tier change — never per frame.
    val perfView = LocalView.current
    if (GlobePerf.ENABLED) {
        DisposableEffect(perfView, quality) {
            GlobePerfState.set(
                perfView,
                if (quality.lite) GlobePerf.STATE_LITE else GlobePerf.STATE_FULL,
            )
            onDispose { GlobePerfState.set(perfView, GlobePerf.STATE_OFF) }
        }
    }

    // Power: the globe is a full-screen Canvas driven by an animation clock.
    // Compose keeps invalidating it at the display refresh rate (90/120 Hz on
    // modern phones) for as long as it is composed — even while the Activity is
    // STOPPED, because an animation is not lifecycle-aware. Gate the whole thing
    // on the lifecycle: when the app isn't at least STARTED (screen off, recents,
    // another app on top) we stop driving the animation entirely and draw one
    // static frame. Leaving composition (navigating away, or HomeScreen swapping
    // the globe out for a flat backdrop while the server sheet is open) cancels
    // the driver outright, because it lives in a LaunchedEffect.
    //
    // The idle rotation is also intentionally slow (a 90s revolution), so
    // redrawing 21k land cells 120x/second buys nothing visible. We snap the
    // animation clock to ~30 fps (20 on the lite path), which is smooth for this
    // content and cuts globe frame work by 2-4x on a high-refresh display.
    val lifecycleOwner = LocalLifecycleOwner.current
    var started by remember { mutableStateOf(true) }
    // Accessibility / battery saver: "Remove animations" sets the system
    // animator duration scale to 0. Compose's own tween animations already
    // honour it through MotionDurationScale, but our hand-rolled clock does not
    // — so a user who has asked for no animation would still get a spinning
    // planet, and would still pay for it. Re-read on every ON_START because the
    // setting can change while we are away.
    var animatorsEnabled by remember { mutableStateOf(true) }
    DisposableEffect(lifecycleOwner) {
        animatorsEnabled = ValueAnimator.areAnimatorsEnabled()
        val observer = LifecycleEventObserver { _, event ->
            when (event) {
                Lifecycle.Event.ON_START -> {
                    started = true
                    animatorsEnabled = ValueAnimator.areAnimatorsEnabled()
                }
                Lifecycle.Event.ON_STOP -> started = false
                else -> Unit
            }
        }
        lifecycleOwner.lifecycle.addObserver(observer)
        onDispose { lifecycleOwner.lifecycle.removeObserver(observer) }
    }
    val animating = started && animatorsEnabled

    // ONE animation clock. Every cyclic value below is a pure function of
    // elapsed time, so a single monotonic millisecond counter reproduces them
    // exactly — but invalidates the Canvas at our chosen cadence rather than the
    // display's, and stops dead when the app is not visible. Elapsed time
    // accumulates across pauses so the sun and the spin resume where they left
    // off instead of snapping back.
    var clockMs by remember { mutableLongStateOf(0L) }
    val frameIntervalMs = quality.frameIntervalMs
    LaunchedEffect(animating, frameIntervalMs) {
        if (!animating) return@LaunchedEffect
        var lastFrame = withFrameMillis { it }
        // `elapsed` free-runs on every vsync; `clockMs` (the snapshot state the
        // Canvas reads) is only PUBLISHED once per frameIntervalMs. Keeping
        // these separate matters: accumulating into the published value instead
        // would discard every sub-threshold frame's delta, and since one frame
        // is 8-16ms and the threshold is 33ms, the clock would never advance at
        // all — a frozen globe on every normal display.
        var elapsed = clockMs
        var lastEmit = clockMs
        while (true) {
            withFrameMillis { frame ->
                // Guard against a huge delta if the choreographer stalls.
                val delta = (frame - lastFrame).coerceIn(0L, 250L)
                lastFrame = frame
                elapsed += delta
                if (elapsed - lastEmit >= frameIntervalMs) {
                    lastEmit = elapsed
                    clockMs = elapsed
                }
            }
        }
    }

    val pulse = cyclePhase(clockMs, 1800L)
    val arcShimmer = cyclePhase(clockMs, 2400L)
    val twinkle = cyclePhase(clockMs, 3600L)
    val idleSpin = cyclePhase(clockMs, 90_000L) * 360f
    // Day/night terminator: the sun's longitude sweeps a full revolution
    // every 2 minutes. Independent of the camera so you can see the shadow
    // crawl across continents while the globe is still / focused.
    val sunSpin = cyclePhase(clockMs, 120_000L) * 360f

    // One-shot precomputation. ~21 k land cells (~5 k on the lite path) stored
    // as packed floats.
    val landSamples = remember(quality) {
        GlobeGeometry.packLandSamples(
            rows = WorldLandmask.rowCount(),
            cols = WorldLandmask.colCount(),
            strideRow = quality.landStride,
            strideCol = quality.landStride,
            isLand = { r, c -> WorldLandmask.isLandCell(r, c) },
        )
    }
    val stars = remember(quality) { precomputeStars(quality.starCount) }
    val landSink = remember { PathQuadSink(Path(), Path(), Path()) }
    val arcPath = remember { Path() }

    val serverPoints = remember(servers) {
        servers.mapNotNull { s ->
            CountryCoords.forCountry(s.countryCode)?.let { ll ->
                Triple(s.id, ll.first, ll.second)
            }
        }
    }
    // The dot pass used to re-derive sin/cos of every server's lat/lon on every
    // frame and iterate a List<Triple<String, Double, Double>> — an iterator
    // allocation per frame, boxed Doubles per read. Same trick as the land
    // buffer: fold the fixed part into packed floats once.
    val serverIds = remember(serverPoints) {
        Array(serverPoints.size) { serverPoints[it].first }
    }
    val serverGeom = remember(serverPoints) { packServerGeometry(serverPoints) }

    val selectedCoord = remember(selectedServerId, serverPoints) {
        serverPoints.firstOrNull { it.first == selectedServerId }
            ?.let { it.second to it.third }
    }

    // Focal target: midpoint of (user, server) when something is selected so
    // the connection arc sweeps across the visible front face.
    val hasFocus = selectedCoord != null
    var focusLatTarget = 0f
    var focusLonTarget = 0f
    if (hasFocus) {
        val sLat = selectedCoord!!.first.toFloat()
        val sLon = selectedCoord.second.toFloat()
        val uLat = userLat.toFloat()
        val uLon = userLon.toFloat()
        val rawDLon = sLon - uLon
        val shiftedSLon = when {
            rawDLon > 180f -> sLon - 360f
            rawDLon < -180f -> sLon + 360f
            else -> sLon
        }
        focusLatTarget = (uLat + sLat) / 2f
        focusLonTarget = (uLon + shiftedSLon) / 2f
    }

    val focus by animateFloatAsState(
        targetValue = if (hasFocus) 1f else 0f,
        animationSpec = tween(1400, easing = FastOutSlowInEasing),
        label = "focus",
    )
    val zoom by animateFloatAsState(
        targetValue = when {
            isConnected -> 1.20f
            hasFocus -> 1.06f
            else -> 1f
        },
        animationSpec = tween(1200, easing = FastOutSlowInEasing),
        label = "zoom",
    )
    val arcProgress by animateFloatAsState(
        targetValue = if (isConnected && hasFocus) 1f else 0f,
        animationSpec = tween(900, delayMillis = if (isConnected) 400 else 0),
        label = "arcProgress",
    )

    val idleLon = if (autoRotate) (idleSpin + userLon.toFloat() - 25f) else userLon.toFloat()
    val effectiveLat = focusLatTarget * focus
    val effectiveLon = lerpAngleDeg(idleLon, focusLonTarget, focus)

    // NOTE: the "light" theme here is Birdo's DIM-light theme (a slate near-dark,
    // #1B1C24) — not a true white theme. These used to be a daylight globe on a
    // near-white #EEF1F8 sky, which painted a glaring white panel into the middle
    // of an otherwise dim UI: exactly the "too bright" complaint the dim theme
    // exists to answer. Both themes now render a NIGHT earth; the dim theme just
    // sits a few steps lighter than the OLED one, and the sky is taken straight
    // from the palette so it can never drift from the app background again.
    val isLight = palette.isLight
    val space = if (isLight) palette.background else Color(0xFF030714)
    val starColor = if (isLight) Color(0xFF5A6580) else Color(0xFFB6C5E2)
    val oceanCore = if (isLight) Color(0xFF26334A) else Color(0xFF1A3050)
    val oceanRim = if (isLight) Color(0xFF141B29) else Color(0xFF071426)
    val landDimC = if (isLight) Color(0xFF33445F) else Color(0xFF1F4364)
    val landMidC = if (isLight) Color(0xFF46628A) else Color(0xFF356D9F)
    val landLitC = if (isLight) Color(0xFF5E86B5) else Color(0xFF59A8E0)
    val atmosphere = if (isLight) Color(0xFF4B7BB0) else Color(0xFF4983C7)
    val rim = if (isLight) Color(0xFF6C9AC9) else Color(0xFF7BB2E6)
    val accent = palette.accent
    val connected = if (isLight) Color(0xFF059669) else Color(0xFF34D399)

    // Shader cache. Keyed on every colour that can end up baked into a gradient,
    // so a theme flip throws the whole cache away rather than leaving a stale
    // shader on screen. Within a theme the slots are keyed on disc geometry, so
    // they miss only while the zoom tween is running.
    val brushes = remember(isLight, atmosphere, oceanCore, oceanRim) { GlobeBrushes() }

    // Sun position: slow east-to-west drift in longitude with a small
    // seasonal-ish latitude tilt so the terminator isn't a perfect vertical.
    val sunLonDeg = 180f - sunSpin
    val sunLatDeg = 12f

    Canvas(modifier = modifier.fillMaxSize()) {
        renderGlobe(
            stars = stars,
            landSamples = landSamples,
            landSink = landSink,
            arcPath = arcPath,
            brushes = brushes,
            quality = quality,
            space = space,
            starColor = starColor,
            oceanCore = oceanCore,
            oceanRim = oceanRim,
            landDim = landDimC,
            landMid = landMidC,
            landLit = landLitC,
            atmosphere = atmosphere,
            rim = rim,
            accent = accent,
            connectedColor = connected,
            isLight = isLight,
            isConnected = isConnected,
            focusLatDeg = effectiveLat,
            focusLonDeg = effectiveLon,
            zoom = zoom,
            twinkle = twinkle,
            pulse = pulse,
            arcShimmer = arcShimmer,
            arcProgress = arcProgress,
            serverIds = serverIds,
            serverGeom = serverGeom,
            selectedServerId = selectedServerId,
            selectedCoord = selectedCoord,
            userLat = userLat,
            userLon = userLon,
            sunLatDeg = sunLatDeg,
            sunLonDeg = sunLonDeg,
        )
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Device tier
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Maps the device onto a [GlobeQuality]. A context with no ActivityManager is
 * not a real device (a stripped test or preview context), so it gets the cheap
 * path rather than the expensive one.
 */
private fun globeQualityFor(context: Context): GlobeQuality {
    val am = context.getSystemService(Context.ACTIVITY_SERVICE) as? ActivityManager
        ?: return GlobeQuality.LITE
    return GlobeQuality.forDevice(am.isLowRamDevice, am.memoryClass)
}

/**
 * Applies the perf HUD's tier pin, if the HUD is compiled in at all.
 *
 * The `GlobePerf.ENABLED` guard is a `static final boolean` in a stock release
 * build, so this returns [auto] without ever subscribing the composition to the
 * debug state.
 */
@Composable
private fun debugQualityOverride(auto: GlobeQuality): GlobeQuality {
    if (!GlobePerf.ENABLED) return auto
    return when (GlobePerfControls.forcedLite.value) {
        null -> auto
        true -> GlobeQuality.LITE
        false -> GlobeQuality.FULL
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Pre-computation (runs once, off the hot path)
// ─────────────────────────────────────────────────────────────────────────────

/** Floats per star in the packed buffer: x, y, baseAlpha, sinPhase, cosPhase, radius. */
private const val STAR_STRIDE = 6

/** Normalized 0..1 phase of a cycle of [periodMs] at time [clockMs]. */
private fun cyclePhase(clockMs: Long, periodMs: Long): Float =
    (clockMs % periodMs).toFloat() / periodMs.toFloat()

/**
 * Star field, packed.
 *
 * The RNG is consumed in exactly the original order (x, y, brightness per star)
 * so positions and brightnesses are bit-identical to previous releases, and a
 * smaller [count] is a strict prefix of the full field rather than a different
 * sky. The twinkle phase is folded into `sin`/`cos` here so the per-frame
 * `sin(twinkle*2PI + phase)` becomes one angle-addition per star: two
 * transcendental calls per frame for the whole field instead of one per star.
 */
private fun precomputeStars(count: Int): FloatArray {
    val rng = Random(0xB16D0L)
    val arr = FloatArray(count * STAR_STRIDE)
    var i = 0
    while (i < arr.size) {
        val x = rng.nextFloat()
        val y = rng.nextFloat()
        val b = rng.nextFloat()
        val phase = b * 13.7f
        arr[i] = x
        arr[i + 1] = y
        arr[i + 2] = b * 0.65f + 0.18f
        arr[i + 3] = sin(phase)
        arr[i + 4] = cos(phase)
        arr[i + 5] = if (b > 0.85f) 1.5f else 0.9f
        i += STAR_STRIDE
    }
    return arr
}

/** Packs `[sinPhi, cosPhi*cos(lon), cosPhi*sin(lon)]` per server, matching [LandSamples]. */
private fun packServerGeometry(points: List<Triple<String, Double, Double>>): FloatArray {
    val arr = FloatArray(points.size * 3)
    var i = 0
    for (p in points) {
        val phi = p.second * PI / 180.0
        val lon = p.third * PI / 180.0
        val cosPhi = cos(phi)
        arr[i] = sin(phi).toFloat()
        arr[i + 1] = (cosPhi * cos(lon)).toFloat()
        arr[i + 2] = (cosPhi * sin(lon)).toFloat()
        i += 3
    }
    return arr
}

private fun lerpAngleDeg(a: Float, b: Float, t: Float): Float {
    var d = (b - a) % 360f
    if (d > 180f) d -= 360f
    if (d < -180f) d += 360f
    return a + d * t
}

// ─────────────────────────────────────────────────────────────────────────────
// Retained per-frame scratch
// ─────────────────────────────────────────────────────────────────────────────

/** Accumulates the continent pass into three retained paths, one per brightness bucket. */
private class PathQuadSink(
    @JvmField val dim: Path,
    @JvmField val mid: Path,
    @JvmField val lit: Path,
) : LandQuadSink {

    fun reset() {
        dim.reset()
        mid.reset()
        lit.reset()
    }

    override fun quad(bucket: Int, px: Float, py: Float, half: Float) {
        val target = when (bucket) {
            GlobeGeometry.BUCKET_LIT -> lit
            GlobeGeometry.BUCKET_MID -> mid
            else -> dim
        }
        // No Rect allocation — primitive moves only.
        target.moveTo(px - half, py - half)
        target.lineTo(px + half, py - half)
        target.lineTo(px + half, py + half)
        target.lineTo(px - half, py + half)
        target.close()
    }
}

/**
 * One cached [Brush] plus the geometry it was built for.
 *
 * [obtain] is `inline` on purpose: a non-inline builder lambda would be
 * allocated on every call, hit or miss, which is exactly the per-frame garbage
 * the cache exists to remove.
 */
private class BrushSlot {
    @JvmField var k0: Float = Float.NaN
    @JvmField var k1: Float = Float.NaN
    @JvmField var k2: Float = Float.NaN
    @JvmField var brush: Brush? = null
}

private inline fun BrushSlot.obtain(a: Float, b: Float, c: Float, build: () -> Brush): Brush {
    val cached = brush
    if (cached != null && k0 == a && k1 == b && k2 == c) return cached
    val fresh = build()
    k0 = a
    k1 = b
    k2 = c
    brush = fresh
    return fresh
}

/** The six radial gradients a globe frame paints. */
private class GlobeBrushes {
    @JvmField val atmosphere = BrushSlot()
    @JvmField val ocean = BrushSlot()
    @JvmField val limb = BrushSlot()
    @JvmField val specular = BrushSlot()
    @JvmField val night = BrushSlot()
    @JvmField val sun = BrushSlot()
}

private val NIGHT_TINT = Color(0xFF02060F)
private val SUN_TINT = Color(0xFFFFE6B0)

// ─────────────────────────────────────────────────────────────────────────────
// Rendering (single hot path, all state passed in by value/reference)
// ─────────────────────────────────────────────────────────────────────────────

@Suppress("LongParameterList", "LongMethod", "ComplexCondition")
private fun DrawScope.renderGlobe(
    stars: FloatArray,
    landSamples: LandSamples,
    landSink: PathQuadSink,
    arcPath: Path,
    brushes: GlobeBrushes,
    quality: GlobeQuality,
    space: Color,
    starColor: Color,
    oceanCore: Color,
    oceanRim: Color,
    landDim: Color,
    landMid: Color,
    landLit: Color,
    atmosphere: Color,
    rim: Color,
    accent: Color,
    connectedColor: Color,
    isLight: Boolean,
    isConnected: Boolean,
    focusLatDeg: Float,
    focusLonDeg: Float,
    zoom: Float,
    twinkle: Float,
    pulse: Float,
    arcShimmer: Float,
    arcProgress: Float,
    serverIds: Array<String>,
    serverGeom: FloatArray,
    selectedServerId: String?,
    selectedCoord: Pair<Double, Double>?,
    userLat: Double,
    userLon: Double,
    sunLatDeg: Float,
    sunLonDeg: Float,
) {
    val w = size.width
    val h = size.height
    if (w <= 0f || h <= 0f) return

    drawRect(color = space, size = size)

    val cx = w * 0.5f
    val cy = h * 0.5f
    val baseR = min(w, h) * 0.46f
    val radius = baseR * zoom
    val atmR = radius * 1.22f
    val atmR2 = atmR * atmR

    // Star field — occluded by the globe disc (with atmosphere padding).
    run {
        // Angle addition: sin(A + phase) == sinA*cosPhase + cosA*sinPhase. Two
        // transcendental calls for the whole field instead of one per star.
        val angle = twinkle * (2.0 * PI).toFloat()
        val sinA = if (quality.twinkle) sin(angle) else 0f
        val cosA = if (quality.twinkle) cos(angle) else 0f
        var s = 0
        while (s < stars.size) {
            val sx = stars[s] * w
            val sy = stars[s + 1] * h
            val baseAlpha = stars[s + 2]
            val sinPhase = stars[s + 3]
            val cosPhase = stars[s + 4]
            val starR = stars[s + 5]
            s += STAR_STRIDE
            val dx = sx - cx
            val dy = sy - cy
            if (dx * dx + dy * dy < atmR2) continue
            val tw = if (quality.twinkle) {
                0.55f + 0.45f * (sinA * cosPhase + cosA * sinPhase)
            } else {
                1f
            }
            drawCircle(
                color = starColor.copy(alpha = baseAlpha * tw),
                radius = starR,
                center = Offset(sx, sy),
            )
        }
    }

    // Outer atmosphere — Fresnel-ish ring that peaks just outside the limb.
    drawCircle(
        brush = brushes.atmosphere.obtain(cx, cy, atmR) {
            Brush.radialGradient(
                colorStops = arrayOf(
                    0.78f to atmosphere.copy(alpha = 0f),
                    0.92f to atmosphere.copy(alpha = if (isLight) 0.22f else 0.36f),
                    1.0f to atmosphere.copy(alpha = 0f),
                ),
                center = Offset(cx, cy),
                radius = atmR,
            )
        },
        radius = atmR,
        center = Offset(cx, cy),
    )

    // Ocean disc with a directional radial gradient (lighter upper-left).
    drawCircle(
        brush = brushes.ocean.obtain(cx, cy, radius) {
            Brush.radialGradient(
                colors = listOf(oceanCore, oceanRim),
                center = Offset(cx - radius * 0.22f, cy - radius * 0.28f),
                radius = radius * 1.05f,
            )
        },
        radius = radius,
        center = Offset(cx, cy),
    )

    // Camera trig — five transcendental calls per FRAME for the whole renderer,
    // plus two for the star twinkle and two for the sun.
    val latRad = focusLatDeg * (PI.toFloat() / 180f)
    val lonRad = focusLonDeg * (PI.toFloat() / 180f)
    val cosLat = cos(latRad)
    val sinLat = sin(latRad)
    val cosLon = cos(lonRad)
    val sinLon = sin(lonRad)

    // Project a (lat, lon) sample. Returns [Offset.Unspecified] if the sample is
    // on the back hemisphere; callers must check. A nullable Offset would BOX —
    // Offset is a value class over a Long — so the sentinel is not a style
    // choice, it is the difference between allocating here and not.
    // (Local function to keep call sites readable; JIT will inline it.)
    fun project(latDeg: Double, lonDeg: Double): Offset {
        val phi = (latDeg * PI / 180.0).toFloat()
        val lam = (lonDeg * PI / 180.0).toFloat() - lonRad
        val cP = cos(phi)
        val sP = sin(phi)
        val sx = cP * sin(lam)
        val sy = sP
        val sz = cP * cos(lam)
        val ty = sy * cosLat - sz * sinLat
        val tz = sy * sinLat + sz * cosLat
        if (tz < 0f) return Offset.Unspecified
        return Offset(cx + sx * radius, cy - ty * radius)
    }

    // ── Continents: project pre-computed samples, cull the back hemisphere,
    // classify the survivors by lighting, accumulate three retained Paths.
    landSink.reset()
    GlobeGeometry.projectLandQuads(
        samples = landSamples,
        cx = cx,
        cy = cy,
        radius = radius,
        cosLat = cosLat,
        sinLat = sinLat,
        cosLon = cosLon,
        sinLon = sinLon,
        cellPx = radius * landSamples.cellSizeRad,
        sink = landSink,
    )
    drawPath(landSink.dim, color = landDim)
    drawPath(landSink.mid, color = landMid)
    drawPath(landSink.lit, color = landLit)

    // Inner limb darkening — clip-free vignette ring near the disc edge.
    drawCircle(
        brush = brushes.limb.obtain(cx, cy, radius) {
            Brush.radialGradient(
                colorStops = arrayOf(
                    0f to Color.Transparent,
                    0.65f to Color.Transparent,
                    1.0f to Color.Black.copy(alpha = if (isLight) 0.10f else 0.30f),
                ),
                center = Offset(cx, cy),
                radius = radius,
            )
        },
        radius = radius,
        center = Offset(cx, cy),
    )

    // Cool-blue rim stroke at the limb.
    drawCircle(
        color = rim.copy(alpha = if (isLight) 0.32f else 0.50f),
        radius = radius - 0.5f,
        center = Offset(cx, cy),
        style = Stroke(width = 1.2f),
    )

    // Specular highlight (upper-left).
    drawCircle(
        brush = brushes.specular.obtain(cx, cy, radius) {
            Brush.radialGradient(
                colors = listOf(
                    Color.White.copy(alpha = if (isLight) 0.18f else 0.10f),
                    Color.Transparent,
                ),
                center = Offset(cx - radius * 0.45f, cy - radius * 0.55f),
                radius = radius * 0.55f,
            )
        },
        radius = radius * 0.55f,
        center = Offset(cx - radius * 0.45f, cy - radius * 0.55f),
    )

    // ── Day / night terminator ────────────────────────────────────────────
    // Project the sun direction into camera space; the dark side is the
    // hemisphere opposite the sun. We draw a soft dark radial overlay
    // centred on the *anti-sun* point on the disc, plus a faint warm
    // highlight at the sub-solar point. Both stay inside the disc by being
    // sized to the radius.
    //
    // Both gradients MOVE every frame, which is the case that used to force a
    // fresh Brush (and therefore a fresh native shader) 30x/second. So the brush
    // is built once with its centre on the disc centre and the canvas is
    // translated instead: a matrix push costs nothing next to a shader rebuild,
    // and the pixels are the same — the circle is drawn at the inverse offset so
    // it lands back on the disc.
    run {
        val sPhi = sunLatDeg * (PI.toFloat() / 180f)
        val sLam = sunLonDeg * (PI.toFloat() / 180f) - lonRad
        val sCp = cos(sPhi)
        val ux = sCp * sin(sLam)
        val uy = sin(sPhi)
        val uz = sCp * cos(sLam)
        val sxCam = ux
        val syCam = uy * cosLat - uz * sinLat
        val szCam = uy * sinLat + uz * cosLat
        val sunPx = cx + sxCam * radius
        val sunPy = cy - syCam * radius
        val antiPx = cx - sxCam * radius
        val antiPy = cy + syCam * radius
        val nightAlpha = if (isLight) 0.22f else 0.55f
        val dayAlpha = if (isLight) 0.10f else 0.18f
        // Night veil — dark blob centred on the anti-solar point, fading out
        // before reaching the sub-solar side. Sized 1.6× radius so the edge
        // falls past the day/night boundary without a visible cutoff.
        val nightBrush = brushes.night.obtain(cx, cy, radius) {
            Brush.radialGradient(
                colorStops = arrayOf(
                    0.0f to NIGHT_TINT.copy(alpha = nightAlpha),
                    0.55f to NIGHT_TINT.copy(alpha = nightAlpha * 0.55f),
                    1.0f to Color.Transparent,
                ),
                center = Offset(cx, cy),
                radius = radius * 1.6f,
            )
        }
        val ndx = antiPx - cx
        val ndy = antiPy - cy
        translate(ndx, ndy) {
            drawCircle(
                brush = nightBrush,
                radius = radius,
                center = Offset(cx - ndx, cy - ndy),
            )
        }
        // Subtle warm sunlit hotspot — only meaningful when the sun is on
        // the visible hemisphere (szCam > 0). The szCam fade is applied as a
        // paint alpha rather than baked into the stops: for a gradient that
        // ends at Color.Transparent, scaling the first stop's alpha and scaling
        // the paint alpha produce the identical ramp, and only one of them
        // needs a new shader.
        if (quality.sunHotspot && szCam > 0f) {
            val sunBrush = brushes.sun.obtain(cx, cy, radius) {
                Brush.radialGradient(
                    colors = listOf(
                        SUN_TINT.copy(alpha = dayAlpha),
                        Color.Transparent,
                    ),
                    center = Offset(cx, cy),
                    radius = radius * 0.7f,
                )
            }
            val sdx = sunPx - cx
            val sdy = sunPy - cy
            translate(sdx, sdy) {
                drawCircle(
                    brush = sunBrush,
                    radius = radius,
                    center = Offset(cx - sdx, cy - sdy),
                    alpha = szCam,
                )
            }
        }
        // Sharper terminator line itself: thin curve where szCam ≈ 0. We
        // approximate by drawing a slim dark stroke along an ellipse passing
        // through the limb perpendicular to the sun vector. Cheap & looks
        // real enough.
        // (skipped — the gradient already sells the curvature.)
    }

    // ── Server dots — ALL visible by default so the user sees every choice.
    // Skip the selected one; it gets a bigger pin in the connection block.
    var k = 0
    while (k < serverIds.size) {
        val base = k * 3
        val id = serverIds[k]
        k++
        if (id == selectedServerId) continue
        // Same packed representation and same cull-before-work order as the
        // land pass, so no trigonometry here either.
        val sinPhi = serverGeom[base]
        val a = serverGeom[base + 1]
        val b = serverGeom[base + 2]
        val sz = a * cosLon + b * sinLon
        val tz = sinPhi * sinLat + sz * cosLat
        if (tz <= GlobeGeometry.FRONT_FACE_EPS) continue
        val sx = b * cosLon - a * sinLon
        val ty = sinPhi * cosLat - sz * sinLat
        val px = cx + sx * radius
        val py = cy - ty * radius
        val depth = tz.coerceIn(0f, 1f)
        val alpha = 0.55f + 0.45f * depth
        // Pulse the halo just a touch so the dots feel alive without being noisy.
        val haloR = 6.5f + pulse * 1.8f
        drawCircle(color = accent.copy(alpha = 0.18f * alpha), radius = haloR, center = Offset(px, py))
        drawCircle(color = accent.copy(alpha = 0.30f * alpha), radius = haloR * 0.62f, center = Offset(px, py))
        drawCircle(color = accent.copy(alpha = 0.95f * alpha), radius = 3.2f, center = Offset(px, py))
        drawCircle(color = Color.White.copy(alpha = 0.85f * alpha), radius = 1.3f, center = Offset(px, py))
    }

    // Connection: great-circle arc on the sphere (slerp + project), then pins.
    if (selectedCoord != null) {
        val arcColor = if (isConnected) connectedColor else accent
        drawGreatCircleArc(
            arcPath = arcPath,
            cx = cx, cy = cy, radius = radius,
            cosLat = cosLat, sinLat = sinLat, cosLon = cosLon, sinLon = sinLon,
            startLat = userLat, startLon = userLon,
            endLat = selectedCoord.first, endLon = selectedCoord.second,
            progress = arcProgress,
            shimmer = arcShimmer,
            color = arcColor,
        )
        val userPos = project(userLat, userLon)
        val srvPos = project(selectedCoord.first, selectedCoord.second)
        if (userPos.isSpecified) {
            val uColor = if (isConnected) connectedColor else accent
            drawGlobePin(userPos, uColor, pulse, small = true)
        }
        if (srvPos.isSpecified) {
            drawGlobePin(srvPos, accent, pulse)
        }
    } else {
        val userPos = project(userLat, userLon)
        if (userPos.isSpecified) {
            drawGlobePin(userPos, accent.copy(alpha = 0.95f), pulse, small = true)
        }
    }
}

/** Mullvad-style pin: outer translucent halo + filled disc + inner white dot. */
private fun DrawScope.drawGlobePin(
    center: Offset,
    color: Color,
    pulse: Float,
    small: Boolean = false,
) {
    val halo = (if (small) 11f else 17f) + pulse * 5f
    val disc = if (small) 5f else 7f
    val inner = if (small) 2f else 2.8f
    drawCircle(color = color.copy(alpha = 0.18f), radius = halo, center = center)
    drawCircle(color = color.copy(alpha = 0.34f), radius = halo * 0.62f, center = center)
    drawCircle(color = color, radius = disc, center = center)
    drawCircle(color = Color.White, radius = inner, center = center)
}

/**
 * Great-circle arc on the unit sphere via slerp, projected segment-by-segment.
 * Naturally clips to the visible hemisphere — the polyline simply breaks when
 * a segment dips behind the limb. Lift > 1 floats the arc just off the
 * surface so it reads cleanly against land.
 *
 * Left on the trigonometric path deliberately: 64 iterations, only when a
 * server is selected, which is three orders of magnitude cheaper than the land
 * pass and not worth the readability cost of packing.
 */
@Suppress("LongParameterList")
private fun DrawScope.drawGreatCircleArc(
    arcPath: Path,
    cx: Float, cy: Float, radius: Float,
    cosLat: Float, sinLat: Float, cosLon: Float, sinLon: Float,
    startLat: Double, startLon: Double,
    endLat: Double, endLon: Double,
    progress: Float,
    shimmer: Float,
    color: Color,
) {
    if (progress <= 0f) return
    val phi1 = (startLat * PI / 180.0).toFloat()
    val lam1 = (startLon * PI / 180.0).toFloat()
    val phi2 = (endLat * PI / 180.0).toFloat()
    val lam2 = (endLon * PI / 180.0).toFloat()
    val ax = cos(phi1) * sin(lam1)
    val ay = sin(phi1)
    val az = cos(phi1) * cos(lam1)
    val bx = cos(phi2) * sin(lam2)
    val by = sin(phi2)
    val bz = cos(phi2) * cos(lam2)
    val dot = (ax * bx + ay * by + az * bz).coerceIn(-1f, 1f)
    val omega = acos(dot)
    if (omega < 1e-3f) return
    val sinO = sin(omega)
    val segments = 64
    val travel = (segments * progress).toInt().coerceAtLeast(2)

    arcPath.reset()
    var pen = false
    var anyDrawn = false
    var seg = 0
    while (seg <= travel) {
        val t = seg.toFloat() / segments
        val a = sin((1f - t) * omega) / sinO
        val b = sin(t * omega) / sinO
        val lift = 1f + 0.045f * sin((PI.toFloat()) * t)
        val ux = (a * ax + b * bx) * lift
        val uy = (a * ay + b * by) * lift
        val uz = (a * az + b * bz) * lift
        // Apply camera (lon rot then lat tilt) — same formula as project().
        val sx = ux * cosLon - uz * sinLon
        val sz0 = ux * sinLon + uz * cosLon
        val ty = uy * cosLat - sz0 * sinLat
        val tz = uy * sinLat + sz0 * cosLat
        if (tz < 0f) {
            pen = false
        } else {
            val px = cx + sx * radius
            val py = cy - ty * radius
            if (!pen) {
                arcPath.moveTo(px, py)
                pen = true
            } else {
                arcPath.lineTo(px, py)
            }
            anyDrawn = true
        }
        seg++
    }
    if (!anyDrawn) return

    // Layered glow + crisp gradient stroke.
    drawPath(arcPath, color = color.copy(alpha = 0.10f), style = Stroke(width = 12f, cap = StrokeCap.Round))
    drawPath(arcPath, color = color.copy(alpha = 0.22f), style = Stroke(width = 6f, cap = StrokeCap.Round))
    drawPath(arcPath, color = color.copy(alpha = 0.95f), style = Stroke(width = 2.4f, cap = StrokeCap.Round))

    // Travelling shimmer once the arc is fully drawn.
    if (progress >= 0.99f) {
        val t = shimmer.coerceIn(0f, 1f)
        val a = sin((1f - t) * omega) / sinO
        val b = sin(t * omega) / sinO
        val ux = (a * ax + b * bx) * 1.045f
        val uy = (a * ay + b * by) * 1.045f
        val uz = (a * az + b * bz) * 1.045f
        val sx = ux * cosLon - uz * sinLon
        val sz0 = ux * sinLon + uz * cosLon
        val ty = uy * cosLat - sz0 * sinLat
        val tz = uy * sinLat + sz0 * cosLat
        if (tz >= 0f) {
            val px = cx + sx * radius
            val py = cy - ty * radius
            drawCircle(color = color.copy(alpha = 0.45f), radius = 6f, center = Offset(px, py))
            drawCircle(color = Color.White.copy(alpha = 0.9f), radius = 2.6f, center = Offset(px, py))
        }
    }
}
