package app.birdo.vpn.ui.components

import androidx.compose.animation.core.FastOutSlowInEasing
import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import app.birdo.vpn.data.model.VpnServer
import app.birdo.vpn.ui.theme.BirdoColors
import app.birdo.vpn.utils.CountryCoords
import kotlin.math.PI
import kotlin.math.acos
import kotlin.math.cos
import kotlin.math.min
import kotlin.math.sin
import kotlin.random.Random

/**
 * Mullvad-style 3D rotating orthographic globe.
 *
 * Performance-critical decisions (v1.3.13 overhaul):
 *  - Land cell positions are flattened into a single `FloatArray` of
 *    `[sinPhi, cosPhi, lonRad]` triples and computed exactly once (lazy via
 *    `remember`). Per frame we walk this packed buffer with a single while
 *    loop — no `Rect`, `Triple`, `Pair`, list/iterator allocations.
 *  - Three retained `Path` objects accumulate land squares per brightness
 *    bucket (directional light → fake spherical shading). Paths are reused
 *    across frames via `Path.reset()`; squares are built with
 *    `moveTo`/`lineTo`/`close` (no `Rect` allocation).
 *  - Idle rotation reads the `InfiniteTransition` value directly. The single
 *    transition state we tween (`focus`) is shortest-arc lerped against the
 *    live idle value, giving smooth bidirectional handoff with no extra
 *    `animateFloatAsState` chasing the spin.
 *  - The great-circle connection arc is generated by slerp on the unit sphere
 *    and projected segment-by-segment, so it follows the curvature of the
 *    planet and naturally clips when it dips behind the limb.
 *  - All heavy rendering lives in a top-level `DrawScope` extension, dodging
 *    the Compose compiler stack-overflow that bit us on v1.3.10 CI.
 */
@Composable
fun WorldGlobe(
    servers: List<VpnServer>,
    selectedServerId: String?,
    isConnected: Boolean,
    modifier: Modifier = Modifier,
    autoRotate: Boolean = true,
    userLat: Double = 51.51,
    userLon: Double = -0.13,
) {
    val palette = BirdoColors.current

    val infinite = rememberInfiniteTransition(label = "globe")
    val pulse by infinite.animateFloat(
        initialValue = 0f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(
            animation = tween(1800, easing = LinearEasing),
            repeatMode = RepeatMode.Restart,
        ),
        label = "pulse",
    )
    val arcShimmer by infinite.animateFloat(
        initialValue = 0f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(
            animation = tween(2400, easing = LinearEasing),
            repeatMode = RepeatMode.Restart,
        ),
        label = "arcShimmer",
    )
    val twinkle by infinite.animateFloat(
        initialValue = 0f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(
            animation = tween(3600, easing = LinearEasing),
            repeatMode = RepeatMode.Restart,
        ),
        label = "twinkle",
    )
    val idleSpin by infinite.animateFloat(
        initialValue = 0f,
        targetValue = 360f,
        animationSpec = infiniteRepeatable(
            animation = tween(90_000, easing = LinearEasing),
            repeatMode = RepeatMode.Restart,
        ),
        label = "idleSpin",
    )

    // One-shot precomputation. ~22 k land cells stored as packed floats.
    val landSamples = remember { precomputeLandSamples() }
    val stars = remember { precomputeStars(STAR_COUNT) }
    val pathDim = remember { Path() }
    val pathMid = remember { Path() }
    val pathLit = remember { Path() }
    val arcPath = remember { Path() }

    val serverPoints = remember(servers) {
        servers.mapNotNull { s ->
            CountryCoords.forCountry(s.countryCode)?.let { ll ->
                Triple(s.id, ll.first, ll.second)
            }
        }
    }
    val selectedCoord = remember(selectedServerId, serverPoints) {
        serverPoints.firstOrNull { it.first == selectedServerId }
            ?.let { it.second to it.third }
    }

    // Focal target: midpoint of (user, server) when something is selected so
    // the connection arc sweeps across the visible front face.
    val hasFocus = selectedCoord != null
    var focusLatTarget = 0f
    var focusLonTarget = 0f
    if (hasFocus) {
        val sLat = selectedCoord!!.first.toFloat()
        val sLon = selectedCoord.second.toFloat()
        val uLat = userLat.toFloat()
        val uLon = userLon.toFloat()
        val rawDLon = sLon - uLon
        val shiftedSLon = when {
            rawDLon > 180f -> sLon - 360f
            rawDLon < -180f -> sLon + 360f
            else -> sLon
        }
        focusLatTarget = (uLat + sLat) / 2f
        focusLonTarget = (uLon + shiftedSLon) / 2f
    }

    val focus by animateFloatAsState(
        targetValue = if (hasFocus) 1f else 0f,
        animationSpec = tween(1400, easing = FastOutSlowInEasing),
        label = "focus",
    )
    val zoom by animateFloatAsState(
        targetValue = when {
            isConnected -> 1.20f
            hasFocus -> 1.06f
            else -> 1f
        },
        animationSpec = tween(1200, easing = FastOutSlowInEasing),
        label = "zoom",
    )
    val arcProgress by animateFloatAsState(
        targetValue = if (isConnected && hasFocus) 1f else 0f,
        animationSpec = tween(900, delayMillis = if (isConnected) 400 else 0),
        label = "arcProgress",
    )

    val idleLon = if (autoRotate) (idleSpin + userLon.toFloat() - 25f) else userLon.toFloat()
    val effectiveLat = focusLatTarget * focus
    val effectiveLon = lerpAngleDeg(idleLon, focusLonTarget, focus)

    val isLight = palette.isLight
    val space = if (isLight) Color(0xFFEEF1F8) else Color(0xFF030714)
    val starColor = if (isLight) Color(0xFF8B95AB) else Color(0xFFB6C5E2)
    val oceanCore = if (isLight) Color(0xFFD8E0EE) else Color(0xFF1A3050)
    val oceanRim = if (isLight) Color(0xFFAEBACF) else Color(0xFF071426)
    val landDimC = if (isLight) Color(0xFF6E7C95) else Color(0xFF1F4364)
    val landMidC = if (isLight) Color(0xFF7E8DA6) else Color(0xFF356D9F)
    val landLitC = if (isLight) Color(0xFF98A6BE) else Color(0xFF59A8E0)
    val atmosphere = if (isLight) Color(0xFF8AAACE) else Color(0xFF4983C7)
    val rim = if (isLight) Color(0xFF6E96C2) else Color(0xFF7BB2E6)
    val accent = palette.accent
    val connected = if (isLight) Color(0xFF1F8F4E) else Color(0xFF44D17E)

    Canvas(modifier = modifier.fillMaxSize()) {
        renderGlobe(
            stars = stars,
            landSamples = landSamples,
            pathDim = pathDim,
            pathMid = pathMid,
            pathLit = pathLit,
            arcPath = arcPath,
            space = space,
            starColor = starColor,
            oceanCore = oceanCore,
            oceanRim = oceanRim,
            landDim = landDimC,
            landMid = landMidC,
            landLit = landLitC,
            atmosphere = atmosphere,
            rim = rim,
            accent = accent,
            connectedColor = connected,
            isLight = isLight,
            isConnected = isConnected,
            focusLatDeg = effectiveLat,
            focusLonDeg = effectiveLon,
            zoom = zoom,
            twinkle = twinkle,
            pulse = pulse,
            arcShimmer = arcShimmer,
            arcProgress = arcProgress,
            serverPoints = serverPoints,
            selectedServerId = selectedServerId,
            selectedCoord = selectedCoord,
            userLat = userLat,
            userLon = userLon,
        )
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Pre-computation (runs once, off the hot path)
// ─────────────────────────────────────────────────────────────────────────────

private const val LAND_STRIDE_ROW = 2
private const val LAND_STRIDE_COL = 2
private const val STAR_COUNT = 90

private class LandSamples(
    /** Packed `[sinPhi, cosPhi, lonRad]` per cell. */
    val data: FloatArray,
    val count: Int,
    /** Angular extent of each cell at the equator (radians). */
    val cellSizeRad: Float,
)

private fun precomputeLandSamples(): LandSamples {
    val rows = WorldLandmask.rowCount()
    val cols = WorldLandmask.colCount()
    val cellLat = PI / rows.toDouble()
    val cellLon = (2.0 * PI) / cols.toDouble()

    var counted = 0
    var r = 0
    while (r < rows) {
        var c = 0
        while (c < cols) {
            if (WorldLandmask.isLandCell(r, c)) counted++
            c += LAND_STRIDE_COL
        }
        r += LAND_STRIDE_ROW
    }

    val arr = FloatArray(counted * 3)
    var idx = 0
    r = 0
    while (r < rows) {
        val phi = (PI / 2.0) - (r + 0.5) * cellLat
        val sinPhi = sin(phi).toFloat()
        val cosPhi = cos(phi).toFloat()
        var c = 0
        while (c < cols) {
            if (WorldLandmask.isLandCell(r, c)) {
                val lon = -PI + (c + 0.5) * cellLon
                arr[idx] = sinPhi
                arr[idx + 1] = cosPhi
                arr[idx + 2] = lon.toFloat()
                idx += 3
            }
            c += LAND_STRIDE_COL
        }
        r += LAND_STRIDE_ROW
    }
    val cellSizeRad = (cellLat.toFloat() * LAND_STRIDE_ROW * 1.55f)
    return LandSamples(arr, idx / 3, cellSizeRad)
}

private fun precomputeStars(count: Int): FloatArray {
    val rng = Random(0xB16D0L)
    val arr = FloatArray(count * 3)
    var i = 0
    while (i < arr.size) {
        arr[i] = rng.nextFloat()
        arr[i + 1] = rng.nextFloat()
        arr[i + 2] = rng.nextFloat()
        i += 3
    }
    return arr
}

private fun lerpAngleDeg(a: Float, b: Float, t: Float): Float {
    var d = (b - a) % 360f
    if (d > 180f) d -= 360f
    if (d < -180f) d += 360f
    return a + d * t
}

// ─────────────────────────────────────────────────────────────────────────────
// Rendering (single hot path, all state passed in by value/reference)
// ─────────────────────────────────────────────────────────────────────────────

@Suppress("LongParameterList", "LongMethod", "ComplexCondition")
private fun DrawScope.renderGlobe(
    stars: FloatArray,
    landSamples: LandSamples,
    pathDim: Path,
    pathMid: Path,
    pathLit: Path,
    arcPath: Path,
    space: Color,
    starColor: Color,
    oceanCore: Color,
    oceanRim: Color,
    landDim: Color,
    landMid: Color,
    landLit: Color,
    atmosphere: Color,
    rim: Color,
    accent: Color,
    connectedColor: Color,
    isLight: Boolean,
    isConnected: Boolean,
    focusLatDeg: Float,
    focusLonDeg: Float,
    zoom: Float,
    twinkle: Float,
    pulse: Float,
    arcShimmer: Float,
    arcProgress: Float,
    serverPoints: List<Triple<String, Double, Double>>,
    selectedServerId: String?,
    selectedCoord: Pair<Double, Double>?,
    userLat: Double,
    userLon: Double,
) {
    val w = size.width
    val h = size.height
    if (w <= 0f || h <= 0f) return

    drawRect(color = space, size = size)

    val cx = w * 0.5f
    val cy = h * 0.5f
    val baseR = min(w, h) * 0.46f
    val radius = baseR * zoom
    val atmR = radius * 1.22f
    val atmR2 = atmR * atmR

    // Star field — occluded by the globe disc (with atmosphere padding).
    run {
        val twoPi = (2.0 * PI).toFloat()
        var s = 0
        while (s < stars.size) {
            val sx = stars[s] * w
            val sy = stars[s + 1] * h
            val sb = stars[s + 2]
            s += 3
            val dx = sx - cx
            val dy = sy - cy
            if (dx * dx + dy * dy < atmR2) continue
            val tw = 0.55f + 0.45f * sin(twinkle * twoPi + sb * 13.7f)
            drawCircle(
                color = starColor.copy(alpha = (sb * 0.65f + 0.18f) * tw),
                radius = if (sb > 0.85f) 1.5f else 0.9f,
                center = Offset(sx, sy),
            )
        }
    }

    // Outer atmosphere — Fresnel-ish ring that peaks just outside the limb.
    drawCircle(
        brush = Brush.radialGradient(
            colorStops = arrayOf(
                0.78f to atmosphere.copy(alpha = 0f),
                0.92f to atmosphere.copy(alpha = if (isLight) 0.22f else 0.36f),
                1.0f to atmosphere.copy(alpha = 0f),
            ),
            center = Offset(cx, cy),
            radius = atmR,
        ),
        radius = atmR,
        center = Offset(cx, cy),
    )

    // Ocean disc with a directional radial gradient (lighter upper-left).
    drawCircle(
        brush = Brush.radialGradient(
            colors = listOf(oceanCore, oceanRim),
            center = Offset(cx - radius * 0.22f, cy - radius * 0.28f),
            radius = radius * 1.05f,
        ),
        radius = radius,
        center = Offset(cx, cy),
    )

    // Camera trig (focus the globe so this point sits at screen centre).
    val latRad = focusLatDeg * (PI.toFloat() / 180f)
    val lonRad = focusLonDeg * (PI.toFloat() / 180f)
    val cosLat = cos(latRad)
    val sinLat = sin(latRad)
    val cosLon = cos(lonRad)
    val sinLon = sin(lonRad)

    // Directional light in camera space (upper-left, towards camera).
    val lx = -0.42f
    val ly = -0.55f
    val lz = 0.72f

    // Project a (lat, lon) sample. Returns -1 in `tz` if the sample is on
    // the back hemisphere; callers must check.
    // (Local function to keep call sites readable; JIT will inline it.)
    fun project(latDeg: Double, lonDeg: Double): Offset? {
        val phi = (latDeg * PI / 180.0).toFloat()
        val lam = (lonDeg * PI / 180.0).toFloat() - lonRad
        val cP = cos(phi)
        val sP = sin(phi)
        val sx = cP * sin(lam)
        val sy = sP
        val sz = cP * cos(lam)
        val ty = sy * cosLat - sz * sinLat
        val tz = sy * sinLat + sz * cosLat
        if (tz < 0f) return null
        return Offset(cx + sx * radius, cy - ty * radius)
    }

    // ── Continents: project pre-computed samples, classify by lighting,
    // accumulate three retained Paths.
    pathDim.reset()
    pathMid.reset()
    pathLit.reset()
    val cellPx = radius * landSamples.cellSizeRad
    val data = landSamples.data
    val limit = landSamples.count * 3
    var i = 0
    while (i < limit) {
        val sinPhi = data[i]
        val cosPhi = data[i + 1]
        val lon = data[i + 2]
        i += 3
        // Inline equivalent of project(cellCenter): saves a function call and
        // skips back-side cells before doing screen coords.
        val lam = lon - lonRad
        val sinL = sin(lam)
        val cosL = cos(lam)
        val sx = cosPhi * sinL
        val sy = sinPhi
        val sz = cosPhi * cosL
        val ty = sy * cosLat - sz * sinLat
        val tz = sy * sinLat + sz * cosLat
        if (tz <= 0.02f) continue
        val px = cx + sx * radius
        val py = cy - ty * radius
        val dot = sx * lx + ty * ly + tz * lz
        // Foreshorten cells near the limb to disguise the rectangular grid.
        val half = cellPx * (0.55f + 0.45f * tz) * 0.5f
        val target = when {
            dot > 0.55f -> pathLit
            dot > 0.20f -> pathMid
            else -> pathDim
        }
        // No Rect allocation — primitive moves only.
        target.moveTo(px - half, py - half)
        target.lineTo(px + half, py - half)
        target.lineTo(px + half, py + half)
        target.lineTo(px - half, py + half)
        target.close()
    }
    drawPath(pathDim, color = landDim)
    drawPath(pathMid, color = landMid)
    drawPath(pathLit, color = landLit)

    // Inner limb darkening — clip-free vignette ring near the disc edge.
    drawCircle(
        brush = Brush.radialGradient(
            colorStops = arrayOf(
                0f to Color.Transparent,
                0.65f to Color.Transparent,
                1.0f to Color.Black.copy(alpha = if (isLight) 0.10f else 0.30f),
            ),
            center = Offset(cx, cy),
            radius = radius,
        ),
        radius = radius,
        center = Offset(cx, cy),
    )

    // Cool-blue rim stroke at the limb.
    drawCircle(
        color = rim.copy(alpha = if (isLight) 0.32f else 0.50f),
        radius = radius - 0.5f,
        center = Offset(cx, cy),
        style = Stroke(width = 1.2f),
    )

    // Specular highlight (upper-left).
    drawCircle(
        brush = Brush.radialGradient(
            colors = listOf(
                Color.White.copy(alpha = if (isLight) 0.18f else 0.10f),
                Color.Transparent,
            ),
            center = Offset(cx - radius * 0.45f, cy - radius * 0.55f),
            radius = radius * 0.55f,
        ),
        radius = radius * 0.55f,
        center = Offset(cx - radius * 0.45f, cy - radius * 0.55f),
    )

    // Faint dots for unselected servers.
    for (sp in serverPoints) {
        if (sp.first == selectedServerId) continue
        val pos = project(sp.second, sp.third) ?: continue
        drawCircle(
            color = accent.copy(alpha = 0.32f),
            radius = 1.6f,
            center = pos,
        )
    }

    // Connection: great-circle arc on the sphere (slerp + project), then pins.
    if (selectedCoord != null) {
        val arcColor = if (isConnected) connectedColor else accent
        drawGreatCircleArc(
            arcPath = arcPath,
            cx = cx, cy = cy, radius = radius,
            cosLat = cosLat, sinLat = sinLat, cosLon = cosLon, sinLon = sinLon,
            startLat = userLat, startLon = userLon,
            endLat = selectedCoord.first, endLon = selectedCoord.second,
            progress = arcProgress,
            shimmer = arcShimmer,
            color = arcColor,
        )
        val userPos = project(userLat, userLon)
        val srvPos = project(selectedCoord.first, selectedCoord.second)
        if (userPos != null) {
            val uColor = if (isConnected) connectedColor else accent
            drawGlobePin(userPos, uColor, pulse, small = true)
        }
        if (srvPos != null) {
            drawGlobePin(srvPos, accent, pulse)
        }
    } else {
        val userPos = project(userLat, userLon)
        if (userPos != null) {
            drawGlobePin(userPos, accent.copy(alpha = 0.95f), pulse, small = true)
        }
    }
}

/** Mullvad-style pin: outer translucent halo + filled disc + inner white dot. */
private fun DrawScope.drawGlobePin(
    center: Offset,
    color: Color,
    pulse: Float,
    small: Boolean = false,
) {
    val halo = (if (small) 11f else 17f) + pulse * 5f
    val disc = if (small) 5f else 7f
    val inner = if (small) 2f else 2.8f
    drawCircle(color = color.copy(alpha = 0.18f), radius = halo, center = center)
    drawCircle(color = color.copy(alpha = 0.34f), radius = halo * 0.62f, center = center)
    drawCircle(color = color, radius = disc, center = center)
    drawCircle(color = Color.White, radius = inner, center = center)
}

/**
 * Great-circle arc on the unit sphere via slerp, projected segment-by-segment.
 * Naturally clips to the visible hemisphere — the polyline simply breaks when
 * a segment dips behind the limb. Lift > 1 floats the arc just off the
 * surface so it reads cleanly against land.
 */
@Suppress("LongParameterList")
private fun DrawScope.drawGreatCircleArc(
    arcPath: Path,
    cx: Float, cy: Float, radius: Float,
    cosLat: Float, sinLat: Float, cosLon: Float, sinLon: Float,
    startLat: Double, startLon: Double,
    endLat: Double, endLon: Double,
    progress: Float,
    shimmer: Float,
    color: Color,
) {
    if (progress <= 0f) return
    val phi1 = (startLat * PI / 180.0).toFloat()
    val lam1 = (startLon * PI / 180.0).toFloat()
    val phi2 = (endLat * PI / 180.0).toFloat()
    val lam2 = (endLon * PI / 180.0).toFloat()
    val ax = cos(phi1) * sin(lam1)
    val ay = sin(phi1)
    val az = cos(phi1) * cos(lam1)
    val bx = cos(phi2) * sin(lam2)
    val by = sin(phi2)
    val bz = cos(phi2) * cos(lam2)
    val dot = (ax * bx + ay * by + az * bz).coerceIn(-1f, 1f)
    val omega = acos(dot)
    if (omega < 1e-3f) return
    val sinO = sin(omega)
    val segments = 64
    val travel = (segments * progress).toInt().coerceAtLeast(2)

    arcPath.reset()
    var pen = false
    var anyDrawn = false
    var seg = 0
    while (seg <= travel) {
        val t = seg.toFloat() / segments
        val a = sin((1f - t) * omega) / sinO
        val b = sin(t * omega) / sinO
        val lift = 1f + 0.045f * sin((PI.toFloat()) * t)
        val ux = (a * ax + b * bx) * lift
        val uy = (a * ay + b * by) * lift
        val uz = (a * az + b * bz) * lift
        // Apply camera (lon rot then lat tilt) — same formula as project().
        val sx = ux * cosLon - uz * sinLon
        val sz0 = ux * sinLon + uz * cosLon
        val ty = uy * cosLat - sz0 * sinLat
        val tz = uy * sinLat + sz0 * cosLat
        if (tz < 0f) {
            pen = false
        } else {
            val px = cx + sx * radius
            val py = cy - ty * radius
            if (!pen) {
                arcPath.moveTo(px, py)
                pen = true
            } else {
                arcPath.lineTo(px, py)
            }
            anyDrawn = true
        }
        seg++
    }
    if (!anyDrawn) return

    // Layered glow + crisp gradient stroke.
    drawPath(arcPath, color = color.copy(alpha = 0.10f), style = Stroke(width = 12f, cap = StrokeCap.Round))
    drawPath(arcPath, color = color.copy(alpha = 0.22f), style = Stroke(width = 6f, cap = StrokeCap.Round))
    drawPath(arcPath, color = color.copy(alpha = 0.95f), style = Stroke(width = 2.4f, cap = StrokeCap.Round))

    // Travelling shimmer once the arc is fully drawn.
    if (progress >= 0.99f) {
        val t = shimmer.coerceIn(0f, 1f)
        val a = sin((1f - t) * omega) / sinO
        val b = sin(t * omega) / sinO
        val ux = (a * ax + b * bx) * 1.045f
        val uy = (a * ay + b * by) * 1.045f
        val uz = (a * az + b * bz) * 1.045f
        val sx = ux * cosLon - uz * sinLon
        val sz0 = ux * sinLon + uz * cosLon
        val ty = uy * cosLat - sz0 * sinLat
        val tz = uy * sinLat + sz0 * cosLat
        if (tz >= 0f) {
            val px = cx + sx * radius
            val py = cy - ty * radius
            drawCircle(color = color.copy(alpha = 0.45f), radius = 6f, center = Offset(px, py))
            drawCircle(color = Color.White.copy(alpha = 0.9f), radius = 2.6f, center = Offset(px, py))
        }
    }
}
