import XCTest

/// K5 connect contract — the SERIALIZED `ConnectBody` / `MultiHopBody`
/// (ConnectWire.swift) against the backend's own schema.
///
/// `contract/vpn-protocol.schema.json` is generated by birdo-web from the code
/// that enforces the wire contract (class-validator on ConnectDto, the
/// `.strict()` zod schema for multi-hop) and vendored into this repo byte for
/// byte; it is carried as a RESOURCE of this test bundle. Both routes refuse
/// unknown keys, so a renamed field is a 400 on every connect — iOS has done
/// that once already (`serverId` for `serverNodeId`, AUDIT-M-DRIFT).
///
/// No third-party validator on iOS: the schema is parsed with
/// JSONSerialization and the handful of keywords the two definitions actually
/// use (`properties` + `additionalProperties: false`, `required`, `type`,
/// `minLength`/`maxLength`, `pattern`, `enum`) are checked by hand. The
/// negative cases below prove that checker bites before the positive cases
/// are trusted.
///
/// Encoding goes through `ConnectWire.makeEncoder()` — the SAME factory
/// APIClient uses — so a key strategy added there is seen here.
final class ConnectContractTests: XCTestCase {

    // MARK: - The vendored schema

    private static let schemaId = "https://birdo.app/contract/vpn-protocol.schema.json"

    /// COMPUTED, not a stored `static let`: `[String: Any]` is not Sendable, and
    /// a static stored property of a non-Sendable type is an error under Swift 6
    /// strict concurrency ("static property 'schema' is not concurrency-safe").
    /// Re-reading a 14 KB resource per access costs nothing at this test count.
    private static var schema: [String: Any] {
        let bundle = Bundle(for: ConnectContractTests.self)
        guard let url = bundle.url(forResource: "vpn-protocol.schema", withExtension: "json") else {
            fatalError("contract/vpn-protocol.schema.json is not in the test bundle — it is listed "
                       + "under BirdoVPNTests in project.yml with buildPhase: resources")
        }
        guard let data = try? Data(contentsOf: url),
              let object = try? JSONSerialization.jsonObject(with: data),
              let dict = object as? [String: Any] else {
            fatalError("contract/vpn-protocol.schema.json is not a JSON object")
        }
        return dict
    }

    private static func definition(_ name: String) -> [String: Any] {
        guard let defs = schema["$defs"] as? [String: Any],
              let def = defs[name] as? [String: Any] else {
            fatalError("$defs.\(name) missing from the vendored schema")
        }
        return def
    }

    private static func properties(of def: [String: Any]) -> [String: [String: Any]] {
        (def["properties"] as? [String: [String: Any]]) ?? [:]
    }

    // MARK: - A deliberately small Draft 2020-12 checker

    /// Every way `body` violates `def`, in words. Empty means valid.
    private static func violations(of body: [String: Any], against def: [String: Any]) -> [String] {
        var out: [String] = []
        let props = properties(of: def)

        if let additional = def["additionalProperties"] as? Bool, additional == false {
            for key in body.keys.sorted() where props[key] == nil {
                out.append("unknown key \(key)")
            }
        }
        for key in (def["required"] as? [String]) ?? [] where body[key] == nil {
            out.append("missing required \(key)")
        }
        for (key, value) in body {
            guard let rule = props[key] else { continue }
            if value is NSNull {
                out.append("\(key): null is not a \(rule["type"] ?? "value")")
                continue
            }
            switch rule["type"] as? String {
            case "string":
                guard let s = value as? String else {
                    out.append("\(key): \(type(of: value)) is not a string"); continue
                }
                if let min = rule["minLength"] as? Int, s.count < min {
                    out.append("\(key): shorter than minLength \(min)")
                }
                if let max = rule["maxLength"] as? Int, s.count > max {
                    out.append("\(key): longer than maxLength \(max)")
                }
                if let pattern = rule["pattern"] as? String, !matches(s, pattern) {
                    out.append("\(key): does not match \(pattern)")
                }
                if let allowed = rule["enum"] as? [String], !allowed.contains(s) {
                    out.append("\(key): not in enum \(allowed)")
                }
            case "boolean":
                // JSONSerialization surfaces JSON booleans as NSNumber(bool);
                // a JSON string "true" is a String and must be refused.
                guard let number = value as? NSNumber, CFGetTypeID(number) == CFBooleanGetTypeID() else {
                    out.append("\(key): \(type(of: value)) is not a boolean"); continue
                }
            default:
                out.append("\(key): checker does not understand type \(rule["type"] ?? "nil") — extend it")
            }
        }
        return out
    }

    private static func matches(_ s: String, _ pattern: String) -> Bool {
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return false }
        let range = NSRange(s.startIndex..<s.endIndex, in: s)
        return regex.firstMatch(in: s, range: range) != nil
    }

    // MARK: - Encoding through the app's encoder

    private func encode<T: Encodable>(_ body: T) throws -> [String: Any] {
        let data = try ConnectWire.makeEncoder().encode(body)
        guard let object = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            XCTFail("body did not encode to a JSON object: \(String(decoding: data, as: UTF8.self))")
            return [:]
        }
        return object
    }

    private func assertValid(_ body: [String: Any], _ def: [String: Any],
                             file: StaticString = #filePath, line: UInt = #line) {
        let problems = Self.violations(of: body, against: def)
        XCTAssertTrue(problems.isEmpty, "expected a valid body, got: \(problems)\nbody: \(body)", file: file, line: line)
    }

    private func assertRefused(_ body: [String: Any], _ def: [String: Any], containing needle: String,
                               file: StaticString = #filePath, line: UInt = #line) {
        let problems = Self.violations(of: body, against: def)
        XCTAssertTrue(problems.contains { $0.contains(needle) },
                      "expected a refusal mentioning '\(needle)', got: \(problems)", file: file, line: line)
    }

    // Shapes that satisfy the schema's patterns and lengths.
    /// 32 bytes of Curve25519 in base64: 43 chars + '='.
    private let wgPublicKey = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    /// ML-KEM-1024 encapsulation key (1568 B) in base64 = 2092 chars; schema 2080..2200.
    private let pqPublicKey = String(repeating: "A", count: 2092)
    private let deviceId = "idfv:6F1A2B3C-4D5E-4F60-8A9B-0C1D2E3F4A5B"

    /// Every field APIClient.getConnectConfig can set, set (PQ on, live rebuild).
    private var fullConnect: ConnectBody {
        ConnectBody(
            serverNodeId: "node-nl-1",
            deviceId: deviceId,
            clientPublicKey: wgPublicKey,
            quantumProtection: true,
            pqClientPublicKey: pqPublicKey,
            pqClientCanDecapsulate: true,
            rebuild: true,
            currentKeyId: "k-0000000001",
            dnsFiltering: true
        )
    }

    private var fullMultiHop: MultiHopBody {
        MultiHopBody(
            entryNodeId: "node-nl-1",
            exitNodeId: "node-de-2",
            deviceId: deviceId,
            clientPublicKey: wgPublicKey,
            quantumProtection: true,
            pqClientPublicKey: pqPublicKey,
            pqClientCanDecapsulate: true,
            rebuild: true,
            currentKeyId: "k-0000000001",
            dnsFiltering: true
        )
    }

    private var connectDef: [String: Any] { Self.definition("ConnectRequest") }
    private var multiHopDef: [String: Any] { Self.definition("MultiHopConnectRequest") }

    // MARK: - The vendored file is the real one

    func testVendoredSchemaIsBirdoWebsAuthoritativeGeneration() {
        XCTAssertEqual(Self.schema["$id"] as? String, Self.schemaId)
        let status = Self.schema["_status"] as? [String: Any]
        XCTAssertEqual(status?["authoritative"] as? Bool, true)
        let definitions = (status?["definitions"] as? [String]) ?? []
        XCTAssertTrue(definitions.contains("ConnectRequest"), "\(definitions)")
        XCTAssertTrue(definitions.contains("MultiHopConnectRequest"), "\(definitions)")
        // The whole reason a rename is fatal: both routes refuse unknown keys.
        XCTAssertEqual(connectDef["additionalProperties"] as? Bool, false)
        XCTAssertEqual(multiHopDef["additionalProperties"] as? Bool, false)
        XCTAssertEqual(Set((multiHopDef["required"] as? [String]) ?? []), ["entryNodeId", "exitNodeId"])
    }

    // MARK: - Positive: what the app sends validates

    func testFullyPopulatedConnectBodyKeysAreASubsetOfTheSchemaAndValid() throws {
        let body = try encode(fullConnect)
        let keys = Set(body.keys)
        let known = Set(Self.properties(of: connectDef).keys)
        XCTAssertTrue(keys.isSubset(of: known), "keys the backend does not know: \(keys.subtracting(known))")
        // Every stored property reached the wire (a `private` or computed
        // field that silently drops out would pass the subset check alone).
        XCTAssertEqual(keys, ["serverNodeId", "deviceId", "clientPublicKey", "quantumProtection",
                              "pqClientPublicKey", "pqClientCanDecapsulate", "rebuild", "currentKeyId",
                              "dnsFiltering"])
        assertValid(body, connectDef)
    }

    func testMinimalConnectBodyOmitsNilOptionalsInsteadOfSendingNull() throws {
        // A first connect with PQ off, not a rebuild: APIClient passes nil for
        // everything but the node and the device. zod/.strict() on the twin
        // route rejects an explicit null; only an ABSENT key passes.
        let body = try encode(ConnectBody(
            serverNodeId: "node-nl-1", deviceId: deviceId, clientPublicKey: wgPublicKey,
            quantumProtection: nil, pqClientPublicKey: nil, pqClientCanDecapsulate: nil,
            rebuild: nil, currentKeyId: nil, dnsFiltering: nil))
        XCTAssertEqual(Set(body.keys), ["serverNodeId", "deviceId", "clientPublicKey"])
        XCTAssertFalse(body.values.contains { $0 is NSNull }, "an explicit null reached the wire: \(body)")
        assertValid(body, connectDef)
    }

    func testFullyPopulatedMultiHopBodyCarriesBothHopIdsAndValidates() throws {
        let body = try encode(fullMultiHop)
        let keys = Set(body.keys)
        let known = Set(Self.properties(of: multiHopDef).keys)
        XCTAssertTrue(keys.isSubset(of: known), "keys the backend does not know: \(keys.subtracting(known))")
        XCTAssertEqual(keys, ["entryNodeId", "exitNodeId", "deviceId", "clientPublicKey", "quantumProtection",
                              "pqClientPublicKey", "pqClientCanDecapsulate", "rebuild", "currentKeyId",
                              "dnsFiltering"])
        // The required pair, by the names the zod schema declares.
        XCTAssertEqual(body["entryNodeId"] as? String, "node-nl-1")
        XCTAssertEqual(body["exitNodeId"] as? String, "node-de-2")
        assertValid(body, multiHopDef)
    }

    func testMinimalMultiHopBodyIsJustTheTwoHopIdsPlusIdentity() throws {
        let body = try encode(MultiHopBody(
            entryNodeId: "node-nl-1", exitNodeId: "node-de-2", deviceId: deviceId,
            clientPublicKey: wgPublicKey, quantumProtection: nil, pqClientPublicKey: nil,
            pqClientCanDecapsulate: nil, rebuild: nil, currentKeyId: nil, dnsFiltering: nil))
        XCTAssertEqual(Set(body.keys), ["entryNodeId", "exitNodeId", "deviceId", "clientPublicKey"])
        XCTAssertFalse(body.values.contains { $0 is NSNull })
        assertValid(body, multiHopDef)
    }

    // MARK: - BirdoShield (D18): dnsFiltering on both routes

    func testDnsFilteringIsASchemaBooleanPresentWhenOnAndAbsentWhenOff() throws {
        // birdo-web PR #465: `dnsFiltering` is an optional boolean on BOTH
        // routes. APIClient sends `true` when the toggle is on and `nil` when
        // it is off, and the encoder drops nil — so an untouched device sends
        // the pre-D18 body, the only one a backend without the field accepts.
        for def in [connectDef, multiHopDef] {
            XCTAssertEqual(Self.properties(of: def)["dnsFiltering"]?["type"] as? String, "boolean")
        }

        let singleOn = try encode(ConnectBody(
            serverNodeId: "node-nl-1", deviceId: deviceId, clientPublicKey: wgPublicKey,
            quantumProtection: nil, pqClientPublicKey: nil, pqClientCanDecapsulate: nil,
            rebuild: nil, currentKeyId: nil, dnsFiltering: true))
        XCTAssertEqual(singleOn["dnsFiltering"] as? Bool, true)
        assertValid(singleOn, connectDef)

        let singleOff = try encode(ConnectBody(
            serverNodeId: "node-nl-1", deviceId: deviceId, clientPublicKey: wgPublicKey,
            quantumProtection: nil, pqClientPublicKey: nil, pqClientCanDecapsulate: nil,
            rebuild: nil, currentKeyId: nil, dnsFiltering: nil))
        XCTAssertNil(singleOff["dnsFiltering"], "off must be ABSENT, got: \(singleOff)")
        assertValid(singleOff, connectDef)

        let multiOn = try encode(MultiHopBody(
            entryNodeId: "node-nl-1", exitNodeId: "node-de-2", deviceId: deviceId,
            clientPublicKey: wgPublicKey, quantumProtection: nil, pqClientPublicKey: nil,
            pqClientCanDecapsulate: nil, rebuild: nil, currentKeyId: nil, dnsFiltering: true))
        XCTAssertEqual(multiOn["dnsFiltering"] as? Bool, true)
        assertValid(multiOn, multiHopDef)

        let multiOff = try encode(MultiHopBody(
            entryNodeId: "node-nl-1", exitNodeId: "node-de-2", deviceId: deviceId,
            clientPublicKey: wgPublicKey, quantumProtection: nil, pqClientPublicKey: nil,
            pqClientCanDecapsulate: nil, rebuild: nil, currentKeyId: nil, dnsFiltering: nil))
        XCTAssertNil(multiOff["dnsFiltering"], "off must be ABSENT, got: \(multiOff)")
        assertValid(multiOff, multiHopDef)
    }

    func testDnsFilteringSentAsAStringIsRefusedOnBothRoutes() throws {
        var single = try encode(fullConnect)
        single["dnsFiltering"] = "true"
        assertRefused(single, connectDef, containing: "dnsFiltering: String is not a boolean")

        var multi = try encode(fullMultiHop)
        multi["dnsFiltering"] = "true"
        assertRefused(multi, multiHopDef, containing: "dnsFiltering: String is not a boolean")
    }

    // MARK: - Negative: the checker bites (run before trusting the green above)

    func testAnUnknownKeyIsRefusedOnBothRoutes() throws {
        var single = try encode(fullConnect)
        single["serverId"] = "node-nl-1"
        assertRefused(single, connectDef, containing: "unknown key serverId")

        var multi = try encode(fullMultiHop)
        multi["entryId"] = "node-nl-1"
        assertRefused(multi, multiHopDef, containing: "unknown key entryId")
    }

    func testARenamedKeyIsRefusedAndARenamedRequiredKeyTwice() throws {
        // The real historical drift: serverNodeId sent as serverId.
        var single = try encode(fullConnect)
        single["serverId"] = single.removeValue(forKey: "serverNodeId")
        assertRefused(single, connectDef, containing: "unknown key serverId")

        var multi = try encode(fullMultiHop)
        multi["entryId"] = multi.removeValue(forKey: "entryNodeId")
        assertRefused(multi, multiHopDef, containing: "unknown key entryId")
        assertRefused(multi, multiHopDef, containing: "missing required entryNodeId")
    }

    func testAMissingHopIdIsRefused() throws {
        var multi = try encode(fullMultiHop)
        multi.removeValue(forKey: "exitNodeId")
        assertRefused(multi, multiHopDef, containing: "missing required exitNodeId")
    }

    func testAMalformedClientPublicKeyIsRefusedOnBothRoutes() throws {
        // 44 chars but no trailing '=': the pattern, not the length, must catch it.
        var single = try encode(fullConnect)
        single["clientPublicKey"] = String(repeating: "A", count: 44)
        assertRefused(single, connectDef, containing: "clientPublicKey: does not match")

        var multi = try encode(fullMultiHop)
        multi["clientPublicKey"] = String(repeating: "A", count: 44)
        assertRefused(multi, multiHopDef, containing: "clientPublicKey: does not match")
    }

    func testACurrentKeyIdOutsideTheKeyIdShapeIsRefused() throws {
        var single = try encode(fullConnect)
        single["currentKeyId"] = "key/with/slashes"
        assertRefused(single, connectDef, containing: "currentKeyId: does not match")
    }

    func testAPqPublicKeyBelowTheMLKEM1024FloorIsRefused() throws {
        var single = try encode(fullConnect)
        single["pqClientPublicKey"] = String(repeating: "A", count: 2079)
        assertRefused(single, connectDef, containing: "pqClientPublicKey: shorter than minLength 2080")
    }

    func testAnExplicitNullIsRefused() throws {
        var single = try encode(fullConnect)
        single["currentKeyId"] = NSNull()
        assertRefused(single, connectDef, containing: "currentKeyId: null is not a string")
    }

    func testABooleanSentAsAStringIsRefused() throws {
        var multi = try encode(fullMultiHop)
        multi["rebuild"] = "true"
        assertRefused(multi, multiHopDef, containing: "rebuild: String is not a boolean")
    }

    func testTheCheckerRefusesATypeItDoesNotUnderstand() {
        // If the backend adds e.g. a numeric field the checker must not pass it
        // silently — it must demand to be extended.
        let def: [String: Any] = ["properties": ["mtu": ["type": "number"]], "additionalProperties": false]
        assertRefused(["mtu": 1280], def, containing: "checker does not understand type number")
    }

    // MARK: - D18 persisted key

    func testTheBirdoShieldDefaultsKeyIsStable() {
        // The toggle is persisted under this key on every installed device.
        // SettingsViewModel writes it and APIClient reads it through the ONE
        // constant; renaming the constant's VALUE would silently read every
        // existing user's toggle as OFF. Change this only with a migration.
        XCTAssertEqual(ConnectWire.dnsFilteringDefaultsKey, "dns_filtering")
    }
}
